from .home import home_view
from .participate_draw import draw_view, participate_draw, start_draw,create_random_users,generate_random_numbers,process_player_participation,create_ticket
from .authentication import register_view, login_view, logout_view
from .draw_list import draw_list
from .draw_win import draw_win,checkingPrize,evaluate_closest_sum,evaluate_correct_numbers,calculate_sum_difference,generate_player_data,create_winner,create_result,get_players